### ISSUE TITLE
Total count on zoomed out map is not equal to count on left side panel.

### ISSUE THREAD

**Issue by loliarz** [konradkalemba/korona.ws#17]
I zoomed out map to see one circle and total count in circle is not equal to total on left side panel. Screen attached.

![Zrzut ekranu 2020-03-15 o 11 16 55](https://user-images.githubusercontent.com/10380550/76699568-ee811100-66ae-11ea-863a-bb851d82e214.png)

**Comment by konradkalemba** [comment]
That's due the fact that in the latest new cases confirmation tweet from MZ there is no city specified in one of the cases therefore one case isn't displayed on the map. I haven't thought of any solution to this problem yet. Thanks for the info.

**Comment by sosite** [comment]
@konradkalemba I think that you should just change way of displaying data from markers and clusters to properly colorized whole provinces or smaller ones like in https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2

**Comment by konradkalemba** [comment]
@sosite Yes, now when they chose not to specify cities on their Twitter it's a top priority task. Any help is welcome.

**Comment by sosite** [comment]
> @sosite Yes, now when they chose not to specify cities on their Twitter it's a top priority task. Any help is welcome.

I can help you create an Android app but JS is not in my skill set unfortunately ;)

**Comment by sosite** [comment]
@konradkalemba What did you think about shrink distance between points before there will be joined in clusters? Or because we stop tracking by cities disable clustering at all?
