### ISSUE TITLE
Add link to more data

### ISSUE THREAD

**Issue by D0han** [konradkalemba/korona.ws#2]
Consider adding link to https://docs.google.com/spreadsheets/d/1ierEhD6gcq51HAm433knjnVwey4ZE5DCnu1bW7PRG3E/htmlview?usp=sharing&sle=true# or maybe even reusing data.  
Linked spreadsheet is not mine.

**Comment by konradkalemba** [comment]
I've already started working on adding more data to the app and I will probably finish it today. Thanks for sending me a link to spreadsheets - they are really well-made.

**Comment by konradkalemba** [comment]
Added more data in the latest release.
