### ISSUE TITLE
Today's people from Podkarpacie

### ISSUE THREAD

**Issue by mhajder** [konradkalemba/korona.ws#24]
It concerns the tweet: https://twitter.com/MZ_GOV_PL/status/1239457262361550851

I heard that they are people from Mielec. But unfortunately I can't confirm it anywhere. I would ask for help in searching for the source.

**Comment by konradkalemba** [comment]
Yes, unfortunately I couldn't find the city name either. I will update the data later basing on the official MZ data from their website. https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2

**Comment by mhajder** [comment]
I found:
https://rzeszow.onet.pl/koronawirus-rzeszow-i-woj-podkarpackie-aktualne-informacje-poniedzialek/3wjkhpt
https://www.se.pl/rzeszow/koronawirus-podkarpacie-kolejne-potwierdzone-przypadki-w-sumie-10-zarazonych-aa-hDnk-evpG-8Tiv.html
And others.
> Potwierdzono dwa nowe przypadki zakażenia wirusem SARS-CoV2 na Podkarpaciu. Chodzi o młoda kobietę z powiatu leżajskiego (stan dobry) oraz mężczyznę w sile wieku z powiatu mieleckiego (stan dobry).
