### ISSUE TITLE
Background map

### ISSUE THREAD

**Issue by kasmar00** [konradkalemba/korona.ws#26]
It appears that you are using Openstreetmap tiles directly from [a/b/c].tile.openstreetmap.org which is (at least) discouraged by [Tile Usage Policy](https://operations.osmfoundation.org/policies/tiles/). OSM Foundation tile servers are under heavy load recently ([twitter post](https://twitter.com/OSM_Tech/status/1239561292572241921)).

I would suggest manually downloading tiles (only for Poland, [there are some ways to limit displaying other regions](https://stackoverflow.com/questions/22155017/can-i-prevent-panning-leaflet-map-out-of-the-worlds-edge)) for required zoom levels (6-11, according to [Tile Calculator by Geofabrik](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=13.909644,48.678226,24.577614,55.181404), it shouldn't be more than 100 MB, or 35 MB if you limit to 6-10) and providing them on your own server (simple web server should be enough). These low zoom tiles aren't generated by OSM servers often, so there should be no major differences between catched-offline tiles and those from tile.osm.org

It was also [pointed](https://forum.openstreetmap.org/viewtopic.php?pid=780100#p780100) by one Openstreetmap contributor that on mobile chrome, the attribution is hidden and one has to scroll the page to see it. It appears that there is a problem with hiding top address bar or the webpage is too long.

![image](https://user-images.githubusercontent.com/19535945/76779238-5288ff80-67ab-11ea-9592-523de4c7afa8.png) ![image](https://user-images.githubusercontent.com/19535945/76779273-63397580-67ab-11ea-938a-374d6ed516df.png)

**Comment by konradkalemba** [comment]
@kasmar00 I see. I wasn't aware of such rules. I will try to host the tiles on my own.

**Comment by kasmar00** [comment]
@konradkalemba I forgot to mention yesterday, there are many tile providers independent from OSM Foundation, some are paid (like [mapbox](https://www.mapbox.com/)) and some only require tokens, you can find them on [switch2osm.org](https://switch2osm.org/using-tiles/).

**Comment by konradkalemba** [comment]
@kasmar00 Okay, thanks. I managed to start a tile server, I don't know though if will it be able to withstand the traffic. I will test it tonight when the traffic will be lower.

**Comment by konradkalemba** [comment]
@kasmar00 I managed to connect to my own tile server but as you can see the city names are not displayed. Do you know what can be the cause?

https://korona-ws-9up6iftmn.now.sh/

**Comment by mhajder** [comment]
> @kasmar00 Okay, thanks. I managed to start a tile server, I don't know though if will it be able to withstand the traffic. I will test it tonight when the traffic will be lower.

If the queries are less than 50k, I would prefer to use MapBox.

**Comment by konradkalemba** [comment]
@mhajder Unfortunately it would cost a lot of money. Our own tile server is now handling all the traffic.

**Comment by mhajder** [comment]
> @mhajder Unfortunately it would cost a lot of money. Our own tile server is now handling all the traffic.

In that case, you can now also pass traffic through CloudFlare with the cache all rule.

**Comment by konradkalemba** [comment]
@mhajder At the moment there is no need for that, but thanks for tip. :)
