### ISSUE TITLE
Latest cases

### ISSUE THREAD

**Issue by chybaDapi** [konradkalemba/korona.ws#3]
Hello,
It would be nice to have latest cases listing next to cities chart tab. Something like in the picture, latest cases on the top. Thanks to that, it would be easier to find new cases, because now you need to remember all numbers and old cases locations to notice a new one, or check every pin on the map to find a case with a latest date.
![image](https://user-images.githubusercontent.com/5363832/76416962-47ddfd00-639c-11ea-8e2d-36bb8297b85a.png)

I wanted to prepare a pull request with suggested changes, but I'm not able to run the app on my local env due to following error: 
> Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).

**Comment by konradkalemba** [comment]
Hi, thanks for the issue. 

The feature you suggested is currently being worked on. 

Regarding error you bumped into while trying to run the app on your own. It is a problem with Firebase connection, which needs to be configured beforehand. I will try write a tutorial how to do so.

Have you ever used Firebase? If so you can create a database there by yourself and I can send you a JSON file of cases. I will also check if I can generate public credentials to give read access to the database the app is using.

**Comment by konradkalemba** [comment]
Implemented in the latest release.

**Comment by konradkalemba** [comment]
@chybaDapi I updated the repository with [contributing guide](https://github.com/konradkalemba/korona.ws/blob/master/CONTRIBUTING.md) if you want to contribute.

**Comment by Sekhmet** [comment]
I see that latest cases on the same date are not sorted properly because time of the day is not stored. Would it be possible to sort them by the time the case was entered to Firebase?

**Comment by konradkalemba** [comment]
@Sekhmet Hmm, you're right - I didn't notice it. I don't know if Firebase stores times of the data modifications. Maybe I can just reverse cases array from the database, which is stored in chronological order and there won't be a need to sort it again. Therefore we will avoid this bug.

**Comment by konradkalemba** [comment]
Should be fixed now.
