### ISSUE TITLE
Create PWA functionality so users can add this page to their mobile/desktop screens and access it more easily.

### ISSUE THREAD

**Issue by thisisui** [konradkalemba/korona.ws#31]
By using Service Workers the page could look and feel as native app without creating native code.

**Comment by konradkalemba** [comment]
Yes, I agree. I've thinking about doing this, but never had time to do so. If there is somebody willing to implement this it would be great.

**Comment by sewerynkalemba** [comment]
Before we proceed with that, I think we should create a basic identification (i.e. icon/logo) for the app -#32 .
