### ISSUE TITLE
Basic identification for the app

### ISSUE THREAD

**Issue by sewerynkalemba** [konradkalemba/korona.ws#32]
Even though a default React app icon is a bit virus-shaped (😛), we should make our own basic identification - what I mean is an icon / a logo. It would also help us in terms of PWA (#31). Feel free to submit one.

**Comment by kkostepski** [comment]
Maybe this icon? https://www.flaticon.com/free-icon/virus_2663820?term=infections&page=1&position=7

If you don't really need custom logo specific for "korona.ws" name, it would be enough, at least better than React icon ;)

**Comment by konradkalemba** [comment]
Logo has been added.
