### ISSUE TITLE
Adding English version 

### ISSUE THREAD

**Issue by maximakymenko** [konradkalemba/korona.ws#40]
Hey guys, there are a lot of foreigners and expats in Poland and some of them don't know Polish. So I decided to take this initiative and add English version of the website using i18n tool.  I'll send you the PR today, hope it will be useful.

**Comment by kkostepski** [comment]
Which tool do you want to use? There are many i18n tools.

**Comment by maximakymenko** [comment]
I've started already with `react-i18n`, cause it fits really good into project and translations are easy to add. I did already about 40% of all translations.

**Comment by maximakymenko** [comment]
Basic internationalisation is added. Should be merged pretty soon.
