### ISSUE TITLE
Zakażenia dzienne

### ISSUE THREAD

**Issue by gosiafelis** [konradkalemba/korona.ws#44]
Cenną wizualizacją byłoby pokazanie ilości zdiagnozowanych zakażeń per dzień na wykresie słupkowym. Lepiej można zaobserwować przyrost (zdiagnozowanych) zakażeń.
 
Taki wykres linkuje tvn24 w swoich artykułach:
https://public.flourish.studio/visualisation/1616542/?utm_source=showcase&utm_campaign=visualisation/1616542

Można go dodać jako tab obecnego wykresu w czasie:
<img width="1177" alt="Screenshot 2020-03-24 at 14 27 56" src="https://user-images.githubusercontent.com/55391173/77430561-aca54880-6ddb-11ea-810a-d0468112242e.png">

PS: Świetna robota z tą mapą - brawo dla wszystkich twórców

**Comment by konradkalemba** [comment]
Faktycznie, dobry pomysł i wydaje się być relatywnie łatwy do wprowadzenia. 👍 

PS. Dzięki za miłe słowa. 😃

**Comment by Kamil-kozlowski** [comment]
Hej, rozpocząłem pracę nad tym :)

**Comment by konradkalemba** [comment]
@Kamil-kozlowski Super, dzięki za info. 👍

**Comment by gosiafelis** [comment]
Dzięki! Cieszę się, że pomysł się przyjął.  👍 
Jeśli będziecie potrzebowali jakiejś pomocy z perspektywy UI/UX/grafika to dawajcie znać.

**Comment by konradkalemba** [comment]
@gosiafelis Jasne, dzięki za propozycję. Jak masz jakieś uwagi co do UX/UI to pisz śmiało. :)

**Comment by gartre** [comment]
Widzę, że wykres dodany! Ekstra 👍 📊 Dzięki serdeczne! Teraz miejmy nadzieję, że słupki na tym wykresie nie będą drastycznie wzrastać 🤞

**Comment by Kamil-kozlowski** [comment]
@gartre oby, oby :)

**Comment by Kamil-kozlowski** [comment]
@konradkalemba Chyba można zamknąć.
