### ISSUE TITLE
Zły tekst w tooltipach w polskiej wersji

### ISSUE THREAD

**Issue by foofaraw** [konradkalemba/korona.ws#45]
W polskiej wersji tooltip przy dziennym wzroście zgonów, potwierdzonych przypadków i dziennym przyroście wykonanych testów wyświetla coś takiego:

![image](https://user-images.githubusercontent.com/24656920/77542645-ccee0980-6ea6-11ea-9b7b-32716d1ea7ba.png)

W angielskiej wersji jest OK, tekst to ładnie sformatowane Today's change.

**Comment by konradkalemba** [comment]
Dzięki za info - faktycznie tak jest.

@maximakymenko Can you verify that? I'd be grateful :)

**Comment by maximakymenko** [comment]
@konradkalemba I'll take a look today ;)
