### ISSUE TITLE
Overlapping sections

### ISSUE THREAD

**Issue by wojdaa** [konradkalemba/korona.ws#6]
On smaller displays (laptop, 14'), the city list section is overlapping infected/fatalities statistics.

Screenshot attached:
<img width="960" alt="2020-03-12_14h09_02" src="https://user-images.githubusercontent.com/10337377/76524870-1a13b980-646b-11ea-8484-559e879d215d.png">

**Comment by konradkalemba** [comment]
Thanks for the info. I will try to get it fixed tonight.

**Comment by PawelKmiecik** [comment]
Maybe instead of fixing that it would be good to move some charts like "Podział na miasta", and new data (saw other enhancement requests) to some side menu that could be hidden in menu strip or sidebar like https://github.com/balloob/react-sidebar

**Comment by konradkalemba** [comment]
Good idea. 👍

**Comment by konradkalemba** [comment]
@wojdaa I changed a bit the layout of the app. Can you check it now?

**Comment by wojdaa** [comment]
@konradkalemba overall it looks better - more info is very useful but I wouldn't add anything more in case the page will loose it's lightness. 

There are still some layout issues though:
<img width="960" alt="2020-03-13_12h46_34" src="https://user-images.githubusercontent.com/10337377/76618636-59084480-6529-11ea-99d0-9a26eea828a6.png">
 
Thanks for the good work you do here :)

**Comment by wojdaa** [comment]
Also - adding accordion (show/hide) to City List section would be nice so that the user can see more map.

**Comment by konradkalemba** [comment]
@wojdaa You're right. Now the content takes too much space on your screen and it covers the map. I will try to make some changes in layout and will let you know, when they are done.

Thanks for your contribution. :)

**Comment by wojdaa** [comment]
Looks way better now - thanks! :)
