### ISSUE TITLE
[bug] Invalid data on prod

### ISSUE THREAD

**Issue by Kamil-kozlowski** [konradkalemba/korona.ws#61]
There is a bug with daily growth chart.
We received some invalid/accumulated data I guess

prod:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/26530372/78235741-5de16800-74d9-11ea-9abb-01d2dc03f90d.png">

<img width="330" alt="Zrzut ekranu 2020-04-2 o 11 28 29" src="https://user-images.githubusercontent.com/26530372/78233268-c3335a00-74d5-11ea-9ab3-4e66b9747647.png">
<img width="341" alt="Zrzut ekranu 2020-04-2 o 11 28 35" src="https://user-images.githubusercontent.com/26530372/78233273-c4fd1d80-74d5-11ea-9df3-305f07736558.png">
<img width="343" alt="Zrzut ekranu 2020-04-2 o 11 28 40" src="https://user-images.githubusercontent.com/26530372/78233275-c595b400-74d5-11ea-8bd9-f0822f575cb6.png">
<img width="247" alt="image" src="https://user-images.githubusercontent.com/26530372/78235431-edd2e200-74d8-11ea-9c4a-be3a43f97252.png">

**Comment by konradkalemba** [comment]
The problem is that an old version of app is cached in your browser. If you refresh the site withour using cache the bug should be gone.

**Comment by konradkalemba** [comment]
@Kamil-kozlowski Unfortunately MZ doesn't provide any info about cured people on their websites or social accounts. Yesterday's number was said by spokesperson of MZ so I decided to include it in our stats. However if MZ will continue not to give the data we will have to stop giving outdated info.

**Comment by Kamil-kozlowski** [comment]
@konradkalemba I see. I thought you weren't aware of it. 
I close the issue as no actions are required.
