### ISSUE TITLE
Bug: Overlapping text in data sources tab

### ISSUE THREAD

**Issue by kolszewska** [konradkalemba/korona.ws#62]
Hi!

The data sources table have some overlapping text - the column names and the first row overlap. (I used the Safari browser - the issue could not be reproduced on the Chrome)

![image](https://user-images.githubusercontent.com/17303358/78263989-eaece700-7502-11ea-8342-eba39a7f1321.png)

**Comment by Kamil-kozlowski** [comment]
@kolszewska please check if it is ok here: https://korona-ws-git-fork-kamil-kozlowski-bugfix-62.konradkalemba.now.sh

**Comment by kolszewska** [comment]
@Kamil-kozlowski yes it does!
