### ISSUE TITLE
dzienny wykres z dnia 30.03 zawiera blad

### ISSUE THREAD

**Issue by PythonWonderWoman** [konradkalemba/korona.ws#65]
dzienny wykres z dnia 30.03 zawiera blad bylo 254 nowych przypadkow a nie 193 jak wskazuje wykres.
zrodla:
https://twitter.com/MZ_GOV_PL/status/1245052138671214592
https://twitter.com/MZ_GOV_PL/status/1244686032966164480

**Comment by konradkalemba** [comment]
@PythonWonderWoman Wszystko jest w porządku, 30.03 było 193 przypadków. Natomiast 31.03 było 256 i z tego okresu są też przesłane tweety.
