### ISSUE TITLE
Chart does not present the current amount of recovered people

### ISSUE THREAD

**Issue by Mr1008** [konradkalemba/korona.ws#69]
Chart does not present the current amount of recovered people. It is somehow misleading because it shows number of deaths.

**Comment by Kamil-kozlowski** [comment]
on graphs there is voivodeship and date oriented data, and for latest deaths and cures we have no details about the region and particular date. The info was like "we have new 50 cured people" without any specific dates given, like on monday - 20 cures confirmed and next day - 30. Therefore it was not added under the hood to the daily graph for instance.
But at the end of the day it somehow should be included @konradkalemba

**Comment by konradkalemba** [comment]
As @Kamil-kozlowski said, there were no dates and voivodeships specified in the data provided by MZ. And it doesn't seem that they will start giving those details. 
I think we'll have to exclude cures count info from voivodeships charts.

**Comment by Mr1008** [comment]
Yes, that's true. There is no voivodeship data for cured. But for a few days now ministry is reporting cured count daily. I think that cured count data from the voivodeship chart could be removed but the sum chart at the bottom could be updated daily now. It would give much better view for a current situation we are in.

**Comment by kolszewska** [comment]
Hi,

to follow up what @Mr1008 wrote adding the cured info to the overall chart will make it less confusing. 

![image](https://user-images.githubusercontent.com/17303358/78975359-39f2d780-7b14-11ea-8c00-17ede3abfdbe.png)

**Comment by konradkalemba** [comment]
@kolszewska Fixed! :)
