### ISSUE TITLE
Redirect to some other source of the data

### ISSUE THREAD

**Issue by bordeux** [konradkalemba/korona.ws#78]
Looks like this project is dead :( 
What do you think to make  domain redirection to https://www.bing.com/covid/local/poland for example?

**Comment by konradkalemba** [comment]
Yes, it had been dead for a while but fortunately it is now working again. :)

**Comment by bordeux** [comment]
Good to hear that! 
[![xos2MnVxe-c](http://img.youtube.com/vi/xos2MnVxe-c/0.jpg)](http://www.youtube.com/watch?v=xos2MnVxe-c "Video Title")
